=== zhuweiwu/web/XML/dtd/books.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY info "information">
<!ENTITY % base "title,author,price">
<!ELEMENT books (book+)>
<!ELEMENT book (%base;)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>


<!ATTLIST book 
	id ID #REQUIRED
	pId IDREF #IMPLIED
	city CDATA #FIXED "CHICAGO"
	lang (EN|CN|JP) "CN"
>

=== zhuweiwu/web/XML/dtd/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd">

<books>
	<book id="bcd" city="CHICAGO">
		<title>JAVA</title>
		<author>aa &info; bb</author>
		<price></price>
	</book>
	<book id="abc" pId="bcd" lang="EN">
		<title>JAVA</title>
		<author></author>
		<price></price>
	</book>
</books>
